"use client";
import React, { useState, useEffect } from 'react';

const TASKS = [
  { id: 1, title: 'Optimize a React Component', language: 'javascript', taskType: 'frontend', description: 'Refactor this component to use proper hooks, memoization, and avoid unnecessary re-renders.' },
  { id: 2, title: 'Write a Binary Search', language: 'python', taskType: 'algorithms', description: 'Implement an iterative binary search function with proper edge case handling.' },
  { id: 3, title: 'Design a REST API Endpoint', language: 'javascript', taskType: 'backend', description: 'Create a well-structured Express.js route handler with validation, error handling, and proper HTTP status codes.' },
  { id: 4, title: 'SQL Query Optimization', language: 'sql', taskType: 'database', description: 'Rewrite this slow subquery using JOINs and proper indexing strategies.' },
];

export default function AiEvaluations() {
  const [selectedTask, setSelectedTask] = useState(TASKS[0]);
  const [code, setCode] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [result, setResult] = useState(null);
  const [history, setHistory] = useState([]);
  const [historyLoading, setHistoryLoading] = useState(true);

  useEffect(() => {
    fetch('/api/evaluations/results')
      .then(r => r.json())
      .then(data => setHistory(data.evaluations || []))
      .catch(() => {})
      .finally(() => setHistoryLoading(false));
  }, []);

  async function handleSubmit() {
    if (!code.trim() || code.trim().length < 10) return;
    setSubmitting(true);
    setResult(null);
    try {
      const res = await fetch('/api/evaluations/submit', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ code, language: selectedTask.language, taskTitle: selectedTask.title, taskType: selectedTask.taskType }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error);
      setResult(data);
      // Add to history
      setHistory(prev => [data.evaluation, ...prev]);
    } catch (err) {
      setResult({ error: err.message });
    } finally {
      setSubmitting(false);
    }
  }

  const scoreColor = (score) => {
    if (score >= 7) return 'text-secondary';
    if (score >= 4) return 'text-yellow-400';
    return 'text-error';
  };

  return (
    <>
      <style dangerouslySetInnerHTML={{ __html: `
        body { background-color: #0B0D12; color: #e2e2e9; min-height: max(884px, 100dvh); -webkit-font-smoothing: antialiased; }
        .glass-card { background: rgba(22,25,34,0.8); border: 1px solid rgba(255,255,255,0.08); backdrop-filter: blur(12px); }
        .material-symbols-outlined { font-variation-settings: 'FILL' 0, 'wght' 400, 'GRAD' 0, 'opsz' 24; }
        .code-editor { font-family: 'JetBrains Mono', 'Fira Code', monospace; resize: none; }
      ` }} />

      <header className="fixed top-0 w-full z-50 bg-surface/80 backdrop-blur-xl border-b border-white/10 h-16 flex items-center justify-between px-4 md:px-8">
        <h1 className="font-headline-md font-bold text-primary">ParableLabs</h1>
        <nav className="hidden md:flex gap-6">
          <a href="/ParablelabsDashboard" className="text-on-surface-variant hover:text-primary font-label-md">Dashboard</a>
          <a href="/DailyChallengesFeedParablelabs" className="text-on-surface-variant hover:text-primary font-label-md">Challenges</a>
        </nav>
      </header>

      {/* ⚠️ Mock AI Banner */}
      <div className="mt-16 w-full bg-yellow-500/10 border-b border-yellow-500/20 px-4 py-2 text-center">
        <p className="text-yellow-400 text-label-sm font-bold">
          ⚠️ MOCK AI — Scores are generated by rule-based keyword heuristics, NOT a real AI/LLM model.
        </p>
      </div>

      <main className="pt-6 pb-12 px-4 md:px-8 max-w-6xl mx-auto">
        <section className="mb-8">
          <h2 className="font-headline-xl text-headline-xl text-on-surface mb-2">AI Code Evaluation</h2>
          <p className="text-on-surface-variant">Submit code for automated scoring. <span className="text-yellow-400">[Mock AI — rule-based scoring]</span></p>
        </section>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Left: Task Selection + Editor */}
          <div className="lg:col-span-2 space-y-6">
            {/* Task Selection */}
            <div className="glass-card rounded-2xl p-6">
              <h3 className="font-headline-sm text-on-surface mb-4">Select Evaluation Task</h3>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                {TASKS.map(task => (
                  <button key={task.id} onClick={() => { setSelectedTask(task); setCode(''); setResult(null); }}
                    className={`p-4 rounded-xl text-left border transition-all ${selectedTask.id === task.id ? 'border-primary/40 bg-primary/10' : 'border-white/10 hover:border-primary/20'}`}>
                    <p className="font-label-md text-on-surface">{task.title}</p>
                    <p className="text-on-surface-variant text-label-sm mt-1">{task.language}</p>
                  </button>
                ))}
              </div>
              <p className="text-on-surface-variant text-label-sm mt-4 pt-4 border-t border-white/8">{selectedTask.description}</p>
            </div>

            {/* Code Editor */}
            <div className="glass-card rounded-2xl p-6">
              <div className="flex items-center justify-between mb-4">
                <h3 className="font-headline-sm text-on-surface">Code Editor</h3>
                <span className="px-3 py-1 bg-primary/10 text-primary border border-primary/20 rounded-lg text-label-sm font-bold">{selectedTask.language}</span>
              </div>
              <textarea
                className="code-editor w-full h-64 bg-[#0B0D12] border border-white/10 rounded-xl p-4 text-sm text-on-surface focus:outline-none focus:border-primary transition-all"
                value={code}
                onChange={e => setCode(e.target.value)}
                placeholder={`Write your ${selectedTask.language} solution here...\n\n// The scoring checks for:\n// - Code length and completeness\n// - Use of core language constructs\n// - Advanced patterns and structure`}
                spellCheck={false}
              />
              <button onClick={handleSubmit} disabled={submitting || code.trim().length < 10}
                className="mt-4 w-full py-3 bg-primary-container hover:bg-primary text-on-primary-container font-label-md rounded-xl transition-all active:scale-[0.98] disabled:opacity-50 flex items-center justify-center gap-2">
                {submitting ? 'Evaluating...' : 'Submit for Evaluation'}
                {!submitting && <span className="material-symbols-outlined text-[18px]">send</span>}
              </button>
            </div>
          </div>

          {/* Right: Results + History */}
          <div className="space-y-6">
            {/* Current Result */}
            {result && (
              <div className={`glass-card rounded-2xl p-6 ${result.error ? 'border-error/30' : 'border-secondary/20'}`}>
                {result.error ? (
                  <p className="text-error">{result.error}</p>
                ) : (
                  <>
                    <div className="flex items-center justify-between mb-4">
                      <h3 className="font-headline-sm text-on-surface">Latest Score</h3>
                      <p className={`font-headline-xl font-black ${scoreColor(result.evaluation?.score)}`}>
                        {result.evaluation?.score}/10
                      </p>
                    </div>
                    <p className="text-secondary text-label-md mb-4">+{result.xpAwarded} XP earned</p>
                    <div className="space-y-2 text-label-sm mb-4">
                      {Object.entries(result.evaluation?.breakdown || {}).map(([k, v]) => (
                        <div key={k} className="flex items-start gap-2">
                          <span className="text-on-surface-variant">{k.replace(/([A-Z])/g, ' $1').trim()}:</span>
                          <span className="text-on-surface">{v}</span>
                        </div>
                      ))}
                    </div>
                    <div className="space-y-1 border-t border-white/8 pt-4">
                      {result.evaluation?.feedback?.map((fb, i) => (
                        <p key={i} className="text-on-surface-variant text-label-sm flex items-start gap-2">
                          <span className="text-primary mt-0.5">→</span>{fb}
                        </p>
                      ))}
                    </div>
                    <p className="text-yellow-400/70 text-[11px] mt-4">⚠️ MOCK AI score</p>
                  </>
                )}
              </div>
            )}

            {/* History */}
            <div className="glass-card rounded-2xl p-6">
              <h3 className="font-headline-sm text-on-surface mb-4">Evaluation History</h3>
              {historyLoading ? (
                <div className="flex justify-center py-8"><div className="w-6 h-6 border-2 border-primary border-t-transparent rounded-full animate-spin" /></div>
              ) : history.length === 0 ? (
                <p className="text-on-surface-variant text-label-sm text-center py-6">No evaluations yet. Submit your first!</p>
              ) : (
                <div className="space-y-3">
                  {history.slice(0, 8).map(e => (
                    <div key={e.id} className="flex items-center justify-between py-3 border-b border-white/5 last:border-0">
                      <div className="flex-1 min-w-0">
                        <p className="font-label-sm text-on-surface truncate">{e.taskTitle}</p>
                        <p className="text-on-surface-variant text-[11px]">{e.language} · {new Date(e.submittedAt).toLocaleDateString()}</p>
                      </div>
                      <span className={`font-bold text-label-md ${scoreColor(e.score)}`}>{e.score}/10</span>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
